---
# tasks file for set-proxy
- name: Set apt-proxy
  ansible.builtin.lineinfile:
    path: "{{ apt_proxy_path }}"
    regexp: "^Acquire::http::Proxy"
    line: 'Acquire::http::Proxy "{{ apt_proxy_ip }}:{{ apt_proxy_port }}";'
    create: true
  become: true
  tags: [ set-proxy, set-apt-proxy ]
