---
# tasks file for common
- name: Git pull dotfile
  ansible.builtin.git:
    repo: "{{ dotfile_repo }}"
    dest: "{{ skel_path }}"
  delegate_to: localhost
  run_once: true
  tags: skel

- name: Put skelfile
  ansible.builtin.copy:
    src: "{{ skel_path }}"
    dest: /etc
    mode: "1644"
  become: true
  tags: skel
